language: node_js

node_js:
  - "8"
  - "9"

addons:
  postgresql: "9.4"

env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis

cache:
  directories:
    - node_modules
    - $NVM_DIR
    - $HOME/.yarn

install:
  - yarn
  - lerna bootstrap

script:
  - scripts/ci

matrix:
  include:
    - addons:
        postgresql: 9.5
      sudo: required
      dist: trusty
