language: node_js

node_js:
  - "8"
  - "4.3.2"

addons:
  postgresql: "9.4"

env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis

cache:
  yarn: true
  directories:
    - node_modules
    - $NVM_DIR
    - packages/graphql-build-pg/node_modules
    - packages/graphql-parse-resolve-info/node_modules
    - packages/postgraphql-build/node_modules
    - packages/graphql-build/node_modules

install:
  - yarn
  - lerna bootstrap

script:
  - scripts/ci

matrix:
  include:
    - addons:
        postgresql: 9.5
      sudo: required
      dist: trusty
