language: node_js

node_js:
  - "8"
  - "4.3.2"

addons:
  postgresql: "9.4"

env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis

cache:
  directories:
    - node_modules
    - $NVM_DIR
    - $HOME/.yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.1
  - export PATH="$HOME/.yarn/bin:$PATH"


install:
  - yarn
  - lerna bootstrap

script:
  - scripts/ci

matrix:
  include:
    - addons:
        postgresql: 9.5
      sudo: required
      dist: trusty
