language: node_js

node_js:
  - "8"
  - "9"

addons:
  postgresql: "9.6"

env:
  TEST_DATABASE_URL: postgres://localhost:5432/travis

cache:
  directories:
    - node_modules
    - $NVM_DIR
    - $HOME/.yarn

install:
  - yarn
  - lerna bootstrap

script:
  - scripts/ci

matrix:
  include:
    - name: PG10
      addons:
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
        postgresql: 10
      env:
        - PGPORT=5433
        - TEST_DATABASE_URL=postgres://travis:travis@localhost:5433/travis
      sudo: false
      dist: trusty
      before_script:
        - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
    - name: PG11
      addons:
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
        postgresql: 11
      env:
        - PGPORT=5434
        - TEST_DATABASE_URL=postgres://travis:travis@localhost:5434/travis
      sudo: false
      dist: trusty
      before_script:
        - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

